Model handling through `baseMdl` module
game-devs-csf/RL-environments pull request #21
Opened 2023-12-27 05:40 UTC by BassedWarrior

- Created file to test the import and export of models using the baseMdl class
- Quitar opción conflictiva de creación de env conda
- Initial mdl.py file
- Initial implementation of cartpoleMdl from baseMdl
- Initial example with baseMdl module
- Fixed syntax errors.
- Eliminar métodos específicos de la baseMdl
- Achieved parity for training, watching and saving
- Fix error with import order
- Achieved total parity with previous version

2023-12-27 06:00 UTC, BassedWarrior commented
Creo que hay varias cosas que si se aprueba este PR, se pueden mejorar, pero 
que dependend de que este PR se apruebe. Y aunque puede abordar #3 y #4, creo 
que no los cierra por completo. Ya que se debe hacer más trabajo para que en 
específico la interfaz de importar y exportar modelos sea mejor.

Un mejor manejo de los paths en los que se guarda y se carga los modelos, por 
ejemplo. Y un mejor manejo de los archivos. Ya que estos commits preservan 
archivos que se volverían fráncamente redundantes, como 
`examples/cartpole_tests` o `examples/cartpole_import_export_models`.

Sin embargo no se si se deben de hacer PRs DESPUÉS de que este se apruebe...o 
si se puede aumentar el scope de este...o se hacen PRs aparte...

2024-01-03 23:40 UTC, A01352283 requested changes
Dejé unos comentarios como sugerencia para poder guardar las q tables en un mismo directorio :)

2024-01-03 23:40 UTC, A01352283 commented on baseMdl/mdl.py
>                  mdl_file = input("Enter model file name: ")
Estuve probando y vi que el modelo se guarda en el directorio donde corres el script, por ejemplo si lo corres en /games, se guarda el modelo en /games. Estaba pensando que sería más conveniente que se guarden en un mismo directorio.

Esto se podría lograr agregando algo así:
```suggestion
                mdl_file = input("Enter model file name: ")
                # Gets the path to the savedModels directory
                models_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), self.models_dir_name)
                if not os.path.exists(models_dir):
                    os.makedirs(models_dir)
                # Gets the path to the saved model file
                mdl_file = os.path.join(models_dir, mdl_file)
``` 
Haciendo eso, se guardan las q-tables en uno que se llama "savedModels" que está en el root del proyecto, y crea el directorio si es que no existe (para evitar que falle en dado caso).

2024-01-03 23:40 UTC, A01352283 commented on baseMdl/mdl.py
Aquí agregar `import os` para que jale lo de guardar los modelos en el directorio de "savedModels"
```suggestion
import os

```

2024-01-03 23:40 UTC, A01352283 commented on baseMdl/mdl.py
>              mdl_file = input("Enter model file name (.npy): ")
Aquí algo similar a lo de ask_to_save, donde se busca en el directorio de savedModels para leer el modelo que se quiere observar:
```suggestion
            mdl_file = input("Enter model file name (.npy): ")
             # Gets the path to the savedModels directory
            models_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), self.models_dir_name)
            # Gets the path to the saved model file
            mdl_file = os.path.join(models_dir, mdl_file)
```

2024-01-03 23:40 UTC, A01352283 commented on baseMdl/mdl.py
> +        self.decay = None
Para que funcione lo de salvar a un directorio en específico, aquí se indica el nombre de dicho directorio:
```suggestion
        self.decay = None
        # For saving and loading models
        self.models_dir_name = "savedModels"
```

2024-01-03 23:47 UTC, A01352283 approved these changes
Agrega los cambios propuestos para guardar y leer los modelos del mismo directorio.

2024-01-03 23:49 UTC, A01352283 commented
Por fin me senté a checar tu PR, una disculpa por la tardanza jeje.

2024-01-03 23:49 UTC, merged